### ISSUE TITLE
git in .dockerignore

### ISSUE THREAD

**Issue by ReFruity** [ReFruity/EzBot#10]
Should be .git instead of git

**Comment by JustMrPhoenix** [comment]
True that, not sure if we actually care about .git being in docker tho

**Comment by ReFruity** [comment]
It's bigger image size, so yes

**Comment by JustMrPhoenix** [comment]
Fixed in 35e42df4071aff82a809acdd8d9b4f6b821dfca3 . No MR for this issue as it does not seem necessary
